### PR TITLE
feat: convert package to esm

### PR DESCRIPTION
**Pull request by guilhermelimak**
This PR converts the package to ESM, allowing updates to dependencies that were converted to ESM already ([p-map in this case](https://github.com/nearform/fastify-secrets-core/pull/208)).

I'm not 100% sure if we should be updating our packages to ESM but since that seems like the way forward in node I think it's a good idea. It is a breaking change tho so I guess we should evaluate if it's worth it.

update: Just realized after seeing CI fail that this would break node v12 support. Not sure how relevant that is since it's a pretty old version but definitely one more thing to take into account.

### CODE REVIEW

**Comment by simoneb** [comment]
@guilhermelimak lgtm, a couple of things:

- node 12 build is failing, probably because of missing support for esm. I think we can safely remove that build and maybe add node 20
- this package is used in the downstream, cloud provider specific secrets packages. I suspect that once we release a new version of this and dependabot bumps this new version in those repos, we'll have to make changes there too

**Comment by guilhermelimak** [comment]
@simoneb I had some [errors](https://github.com/nearform/fastify-secrets-core/actions/runs/4808622416/jobs/8558828590#step:6:106) when running the tests, it looks like the way sinon used to create stubs is not supported anymore in version 20. I didn't find any issues or posts regarding a similar error on their repo so I'm not 100% sure that's the case (v20 is relatively new so maybe that's it tho). Do we have any other projects that you know of that use sinon and run fine on node v20?

About the other point, I searched here and found around [12 packages](https://github.com/search?q=path%3A**%2Fpackage.json+fastify-secrets-core&type=code) that depend on this one. Although that's quite a bit it  seems like they're very simple so the changes should be relatively quick to do (optimistically). However the work would also need to be done on their consumers and so on. I'm just not sure about the benefits to justify all the work since we could just not update `p-map` here and everything would keep working fine. What do you think?

**Comment by simoneb** [comment]
The dependent packages are all ours so not a big deal, but considering the issue we're having with sinon, I don't see much value in moving to ESM besides figuring out why it's failing on Node 20. Hence, I'd stick with CJS and see if the sinon problem goes away.

**Comment by simoneb** [comment]
@guilhermelimak what's the status here?

**Comment by guilhermelimak** [comment]
@simoneb I think we should leave it as is and close this PR then. I don't see much benefit for the amount of work needed right now. If you think we should pursue this we can keep it open and I can create an issue to track the rest of the work.

**Comment by simoneb** [comment]
agreed

**Pull request closed without merging**
